### ISSUE TITLE
Plugin doesn't launch

### ISSUE THREAD

**Issue by FrancisVega** [kaleidocode-app/regulator#1]
Hi!, thanks you very much for the plugin. I love it :D

I get this error in the Figma console in some documents :S 

I can't reproduce the error from a blank canvas btw...

```
------- Clearing and silencing console.log from Figma -------
figma_app.288fa60fa03f84190010a224532891bf.min.js:359 TypeError: value has no property
    at <anonymous> (PLUGIN_9_SOURCE:110)
    at forEach (native)
    at ./src/code.ts (PLUGIN_9_SOURCE:116)
    at call (native)
    at __webpack_require__ (PLUGIN_9_SOURCE:20)
    at <anonymous> (PLUGIN_9_SOURCE:84)
    at <anonymous> (PLUGIN_9_SOURCE:146)
    at call (native)
    at <eval> (PLUGIN_9_SOURCE:149)
------- Restoring console.log functionality in Figma --------
```

**Comment by lijxse** [comment]
Yes, Me too.

**Comment by FrancisVega** [comment]
Well, it seems that it doesn't work when there are gradient styles

**Comment by miguelsolorio** [comment]
@FrancisVega thanks for troubleshooting, you're right that this breaks with gradients. For now I will unblock this but it will take some time to adjust the color in the list to properly show the correct gradient colors (for now it'll be a gray).

**Comment by miguelsolorio** [comment]
Pushed an update to the plugin and this should now work, please let me know if it doesn't.
