### ISSUE TITLE
Regulator doesn't work

### ISSUE THREAD

**Issue by MarioBiancolella** [kaleidocode-app/regulator#11]
I can not explain why "Regulator" does not work, but it happened. No matter how many times you try to restart Figma, nothing changes.

**Comment by miguelsolorio** [comment]
Can you go into the Figma menu and search for "Console":

![image](https://user-images.githubusercontent.com/35271042/97191049-b624d380-1763-11eb-8c79-8930515017bc.png)

Which will open a panel in the bottom. Then try running the plugin and then taking a screenshot of the results in the panel:

![image](https://user-images.githubusercontent.com/35271042/97191124-cb016700-1763-11eb-864f-5a313a160b28.png)

**Comment by MarioBiancolella** [comment]
Here we are! ;-)
https://user-images.githubusercontent.com/36635785/97191665-649e3800-17a7-11eb-802f-682f9e49948b.jpg

**Comment by miguelsolorio** [comment]
Ah ok this looks like it's an issue with gradients, something must've changed in the Figma API. Do you have any color styles that contain gradients?

**Comment by MarioBiancolella** [comment]
It could be but i'm not so sure and this because i'm not the owner of this file created a few month ago from a colleague of mine. I hope I've helped you.

**Comment by miguelsolorio** [comment]
I just pushed an update to the plugin, can you try reloading your file and trying again?

**Comment by MarioBiancolella** [comment]
It works! Thanks for your support and obviously for your cool and useful plugin. 👍
