### ISSUE TITLE
Feature Request: it is possible to add replace and $current name

### ISSUE THREAD

**Issue by E-tek** [kaleidocode-app/regulator#2]
I usually naming my styles as i create them, but I find many cases when I need to bulk rename them, usually it will be only a part of the name, , removing, changing parts of the name, or adding prefix / Suffix to the existed name.
As this is the only solution I know for bulk renaming styles, it will be very helpful
Thanks in advance

**Comment by miguelsolorio** [comment]
@E-tek so what you're wanting is something similar to "Find and Replace" but for color styles?

![image](https://user-images.githubusercontent.com/35271042/70340325-754b6580-1805-11ea-90fa-c7a612a8f5bb.png)

**Comment by E-tek** [comment]
@misolori 
Thanks for the response, Sorry for the delayed response.
Yes exactly, be able to change specific part of string.
find and replace is also excellent. 
but as a basic feature I was looking for a way to batch rename and orginize styles with '/' 
For example:

- Control/idle
- Control/over

Or

- My Theme/Control/idle
- My Theme/Input/idle

Another feature is add / change symbols prefix in the beginging of a name

- $stylename
- --arrtibutename
-  .stylename

Used for exporting the styles to design tokens, css, SASS, etc...
like this plugin
https://www.figma.com/c/plugin/742750636238601912/CSSGen
That will generate My Theme/My Style as --my_theme_my_style

**Comment by gossi** [comment]
A search/replace will do that @E-tek 😊

I'm also super happy in favor of search/replace addition to that plugin. Reminds me a little of [NameChanger](https://mrrsoftware.com/namechanger/).

**Comment by miguelsolorio** [comment]
This is currently in the works, sneak peek:

![Kapture 2020-02-04 at 11 17 31](https://user-images.githubusercontent.com/35271042/73779019-ed200880-4740-11ea-98bc-bc3477202d1c.gif)

**Comment by miguelsolorio** [comment]
This is now updated in the Figma plugin store, please give it a whirl and let me know what you think. I almost added a toggle to "Select All" but wasn't sure how often people would want to use that.

https://www.figma.com/c/plugin/772054917007268360/Regulator
