### ISSUE TITLE
Feature request: Wildcard for original name

### ISSUE THREAD

**Issue by okyr-ux** [kaleidocode-app/regulator#4]
It would be awesome to have «$B» to insert the original style's name (I would prefer $N, but I guess it's already impossible, because $n inserts a number).

Let's say, I have 50 styles with some names. I want to group them, so I want to write: «Group 1/$B» and it would rename:
Dark blue → Group 1/Dark blue
Blue →  Group 1/Blue
Green →  Group 1/Green
etc.

**Comment by miguelsolorio** [comment]
👍 Love the idea, let me see what I can do.

**Comment by miguelsolorio** [comment]
You can now use `$&` to rename with the current name (it's the same syntax as Figma's bulk renamer):

![Kapture 2020-02-18 at 22 09 22](https://user-images.githubusercontent.com/35271042/74806728-a3383600-529b-11ea-8aaa-9c817efec14e.gif)
